blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/predakanga/textual-python-repl/security/advisories/new
    about: Please report vulnerabilities privately.
