name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      description: The problem or use case, rather than a particular solution.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Ideas
      description: How you think it could work, if you have something in mind.
